name: Build RACE External Project
description: Use ext-builder to build an external project for RACE

inputs:
  target:
    description: Target platform and architecture
    required: true
  path:
    description: Path to project build context
    default: .
  cache:
    description: Name of build cache directory
    default: ${{ github.workspace }}/ext-cache
  builder-repository:
    description: ext-builder repository
    default: ${{ github.repository_owner }}/ext-builder
  builder-ref:
    description: ext-builder repo ref to checkout
    default: main
  builder-tag:
    description: ext-builder image tag to run
    default: v1

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.builder-repository }}
        ref: ${{ inputs.builder-ref }}
        path: 'ext-builder'

    - uses: docker/setup-qemu-action@v2
      if: inputs.target == 'linux-arm64-v8a'
      with:
        platforms: 'arm64,arm'

    - shell: bash
      run: |
        ./ext-builder/build.py ${{ inputs.path }} \
          --target ${{ inputs.target }} \
          --image ghcr.io/${{ inputs.builder-repository }}:${{ inputs.builder-tag }} \
          --cache-dir ${{ inputs.cache }}
