name: Build External Package

on:
  workflow_call:
    inputs:
      skip-linux-x86_64:
        default: false
        type: boolean
      skip-linux-arm64-v8a:
        default: false
        type: boolean
      skip-android-x86_64:
        default: false
        type: boolean
      skip-android-arm64-v8a:
        default: false
        type: boolean

jobs:
  build-ext:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Build Linux x86_64
        if: inputs.skip-linux-x86_64 == false
        uses: tst-race/ext-build-action@v1
        with:
          target: linux-x86_64

      - name: Build Android x86_64
        if: inputs.skip-android-x86_64 == false
        uses: tst-race/ext-build-action@v1
        with:
          target: android-x86_64

      - name: Build Android arm64-v8a
        if: inputs.skip-android-arm64-v8a == false
        uses: tst-race/ext-build-action@v1
        with:
          target: android-arm64-v8a

      - name: Build Linux arm64-v8a
        if: inputs.skip-linux-arm64-v8a == false
        uses: tst-race/ext-build-action@v1
        with:
          target: linux-arm64-v8a

      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            ext-cache/*.log
            ext-cache/*.tar.gz
          retention-days: 10

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ext-cache/*.tar.gz
